### ISSUE TITLE
Cmake with packages

### ISSUE THREAD

**Issue by araven** [compnerd/swift-build-examples#15]
How could we use cmake only with the package features of swift ?

**Comment by compnerd** [comment]
What do you mean by the package features of Swift?

**Comment by araven** [comment]
> What do you mean by the package features of Swift?

I had in mind the swift package manager, that appears to be (partly) in conflict with the cmake infrastructure. But may be not?
My point is that I have an external C library packed with a package.swift in a module folder to be incorporated with any swift files and I do not see how to manage that with cmake now. 
I will be happy to share your thoughts on that.

**Comment by compnerd** [comment]
You are trying to use a CMake package which s-p-m, which is not the point of this project - this project is to show how to use CMake to build Swift code.  AFAIK, s-p-m does not support non-s-p-m build systems.  I've usually addressed that by using CMake to build projects rather than s-p-m.  Not sure that there is anything that can be done here for that.  If I've misunderstood something, please re-open the issue.
